server:
  port: 8082
spring:
  cloud:
    nacos:
      #服务发现
      discovery:
        server-addr: 127.0.0.1:8848
        #namespace: affa7d4f-e1dc-42c4-b871-3a73d4388b33
        enabled: true
      username: nacos
      password: nacos
    sentinel:
      eager: true  #是否饥饿加载
      transport:
        dashboard: 127.0.0.1:7070  #Sentinel 控制台地址
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    com:
      alibaba:
        cloud:
          nacos:
            client: debug
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    health:
      show-details: always

dubbo:
  scan:
    base-packages: com.hepo.c2c.social.govern.reviewer.service
  protocols:
    dubbo:
      name: dubbo  #协议名称
      port: 20990  #协议端口，-1 表示自增端口，从 20880 开始
  registry:
    address: spring-cloud://127.0.0.1:8848  # 指定 Dubbo 服务注册中心的地址
  service:
    version: 1.0.0  #版本号
  metadata-report:
    address: nacos://127.0.0.1:8848