server:
  port: 8081
spring:
  cloud:
    nacos:
      #服务发现
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true
      username: nacos
      password: nacos
logging:
  level:
    com:
      alibaba:
        cloud:
          nacos:
            client: debug
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    health:
      show-details: always
#dubbo配置
dubbo:
  version: 1.0.0
  registry:
    address: nacos://localhost:8848/?username=nacos&password=nacos
  scan:
    base-packages:
      - com.hepo.c2c.social.govern.reward
